import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { PlatformClient } from '../platform/client.js';
import { runTool } from './helpers.js';

const stepUpTokenParam = z
  .string()
  .min(16)
  .max(256)
  .optional()
  .describe(
    'Step-up token generated by a human (POST /api/v1/auth/step-up or the nServers app). ' +
      'Required for sensitive actions (reinstall, reset_root_password, console access, ' +
      'protected servers). If absent and the API demands it, the tool returns approval_required.'
  );

export function registerWriteTools(server: McpServer, client: PlatformClient): void {
  server.tool(
    'vps_action',
    'Run a power action on a VPS: start, stop, restart, poweroff, reinstall, reset_root_password or console_session. Returns an async operation to poll via operation_get. Requires ability: vps:control. Sensitive actions and protected servers require stepUpToken from a human.',
    {
      vpsId: z.string().min(1).describe('VPS identifier from vps_list'),
      action: z
        .enum(['start', 'stop', 'restart', 'poweroff', 'reinstall', 'reset_root_password', 'console_session'])
        .describe('Power/lifecycle action to execute'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ vpsId, action, stepUpToken }) =>
      runTool(client, 'vps_action', () =>
        client.fetchApi(
          `/api/v1/vps/${encodeURIComponent(vpsId)}/actions/${encodeURIComponent(action)}`,
          { method: 'POST', stepUpToken }
        )
      )
  );

  server.tool(
    'vps_snapshot_create',
    'Create a snapshot of a VPS disk. Returns an async operation. Requires ability: vps:control.',
    {
      vpsId: z.string().min(1).describe('VPS identifier from vps_list'),
      name: z.string().min(1).max(64).optional()
        .describe('Snapshot name; server assigns one when omitted'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ vpsId, name, stepUpToken }) =>
      runTool(client, 'vps_snapshot_create', () =>
        client.fetchApi(`/api/v1/vps/${encodeURIComponent(vpsId)}/snapshots`, {
          method: 'POST',
          body: name ? { name } : {},
          stepUpToken,
        })
      )
  );

  server.tool(
    'vps_snapshot_restore',
    'Restore a VPS to a named snapshot. Destructive: current disk state is replaced. Returns an async operation. Requires ability: vps:control and usually stepUpToken.',
    {
      vpsId: z.string().min(1).describe('VPS identifier from vps_list'),
      name: z.string().min(1).describe('Snapshot name from vps_snapshots_list'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ vpsId, name, stepUpToken }) =>
      runTool(client, 'vps_snapshot_restore', () =>
        client.fetchApi(
          `/api/v1/vps/${encodeURIComponent(vpsId)}/snapshots/${encodeURIComponent(name)}/restore`,
          { method: 'POST', stepUpToken }
        )
      )
  );

  server.tool(
    'vps_snapshot_delete',
    'Delete a named VPS snapshot. Requires ability: vps:control.',
    {
      vpsId: z.string().min(1).describe('VPS identifier from vps_list'),
      name: z.string().min(1).describe('Snapshot name from vps_snapshots_list'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ vpsId, name, stepUpToken }) =>
      runTool(client, 'vps_snapshot_delete', () =>
        client.fetchApi(
          `/api/v1/vps/${encodeURIComponent(vpsId)}/snapshots/${encodeURIComponent(name)}`,
          { method: 'DELETE', stepUpToken }
        )
      )
  );

  server.tool(
    'vps_protection_toggle',
    'Toggle protected mode on a VPS. While protected, power actions require step-up verification. Requires ability: vps:control.',
    {
      vpsId: z.string().min(1).describe('VPS identifier from vps_list'),
      enabled: z.boolean().describe('Enable (true) or disable (false) protected mode'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ vpsId, enabled, stepUpToken }) =>
      runTool(client, 'vps_protection_toggle', () =>
        client.fetchApi(`/api/v1/vps/${encodeURIComponent(vpsId)}/protection`, {
          method: 'POST',
          body: { enabled },
          stepUpToken,
        })
      )
  );

  server.tool(
    'ssh_key_create',
    'Register a new SSH public key on the account for VPS access. Requires ability: vps:control.',
    {
      name: z.string().min(1).max(120).describe('Key label'),
      publicKey: z
        .string()
        .min(20)
        .describe('OpenSSH public key (ssh-ed25519/ssh-rsa ...)'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ name, publicKey, stepUpToken }) =>
      runTool(client, 'ssh_key_create', () =>
        client.fetchApi('/api/v1/ssh-keys', {
          method: 'POST',
          body: { name, public_key: publicKey },
          stepUpToken,
        })
      )
  );

  server.tool(
    'ssh_key_delete',
    'Remove an SSH public key from the account. Requires ability: vps:control.',
    {
      sshKeyId: z.string().min(1).describe('SSH key identifier from ssh_keys_list'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ sshKeyId, stepUpToken }) =>
      runTool(client, 'ssh_key_delete', () =>
        client.fetchApi(`/api/v1/ssh-keys/${encodeURIComponent(sshKeyId)}`, {
          method: 'DELETE',
          stepUpToken,
        })
      )
  );

  server.tool(
    'game_server_action',
    'Run a power action on a game server (start, stop, restart, kill). Returns an async operation. Requires ability: game_servers:control.',
    {
      gameServerId: z.string().min(1).describe('Game server identifier'),
      action: z.enum(['start', 'stop', 'restart', 'kill']).describe('Power action'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ gameServerId, action, stepUpToken }) =>
      runTool(client, 'game_server_action', () =>
        client.fetchApi(
          `/api/v1/game-servers/${encodeURIComponent(gameServerId)}/actions/${encodeURIComponent(action)}`,
          { method: 'POST', stepUpToken }
        )
      )
  );

  server.tool(
    'ai_run_cancel',
    'Cancel a running nAI agent run. Requires ability: ai:ask.',
    {
      runId: z.string().min(1).describe('Run identifier from ai_runs_list'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ runId, stepUpToken }) =>
      runTool(client, 'ai_run_cancel', () =>
        client.fetchApi(`/api/v1/ai/runs/${encodeURIComponent(runId)}/cancel`, {
          method: 'POST',
          stepUpToken,
        })
      )
  );

  server.tool(
    'ai_approval_decide',
    'Approve or reject a pending nAI run approval request. Requires ability: ai:ask.',
    {
      approvalId: z.string().min(1).describe('Approval identifier from ai_approvals_list'),
      decision: z.enum(['approve', 'reject']).describe('Human decision'),
      reason: z.string().max(500).optional().describe('Optional decision note'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ approvalId, decision, reason, stepUpToken }) =>
      runTool(client, 'ai_approval_decide', () =>
        client.fetchApi(
          `/api/v1/ai/runs/approvals/${encodeURIComponent(approvalId)}`,
          { method: 'POST', body: { decision, reason }, stepUpToken }
        )
      )
  );

  server.tool(
    'service_action',
    'Run an action on a billing-linked service (hosting/streaming via the WHMCS bridge), e.g. reboot a service node. Requires an authenticated client-area token.',
    {
      serviceKey: z.string().min(1).describe('Service key from services_list'),
      action: z.string().min(1).max(64).describe('Service action name (e.g. reboot)'),
      stepUpToken: stepUpTokenParam,
    },
    async ({ serviceKey, action, stepUpToken }) =>
      runTool(client, 'service_action', () =>
        client.fetchApi(
          `/site/v1/services/${encodeURIComponent(serviceKey)}/actions/${encodeURIComponent(action)}`,
          { method: 'POST', stepUpToken }
        )
      )
  );
}
